name: co3kernel_build_expr
on:
  workflow_dispatch:
    inputs:
      KERNEL_NAME:
        description: "自定义 Linux version 字符串"
        required: true
        default: '-android13-8-o-01129-g2e2297c38782'
      KERNEL_VER:
        description: "自定义 KernelSU 版本号"
        required: true
        default: 'default'
      TMPFS_XATTR:
        description: "tmpfs 支持扩展属性"
        required: true
        type: choice
        options:
          - 'Y'
          - 'N'
        default: 'Y'
      BBR_ALGORITHM:
        description: "tcp 默认使用 bbr 算法"
        required: true
        type: choice
        options:
          - 'Y'
          - 'N'
        default: 'Y'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git
        run: |
          git config --global user.name "DogEZ"
          git config --global user.email "DdogezD@gmail.com"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl ocaml ocaml-findlib opam
          sudo apt install -y libpcre3-dev pkg-config
          opam init -y --disable-sandboxing
          eval $(opam env)
          opam update
          opam install -y --assume-depexts coccinelle.1.3.0

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/sm8550 -m oneplus_open_v.xml --depth=1
          repo sync
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion

      - name: prepare file
        run: |
          mkdir -p kernel_workspace/kernel_files
          cp kernel_workspace/kernel_platform/common/crypto/lz4hc.c ./kernel_workspace/kernel_files/
          cp kernel_workspace/kernel_platform/common/crypto/lz4.c ./kernel_workspace/kernel_files/
          cp kernel_workspace/kernel_platform/common/fs/f2fs/compress.c ./kernel_workspace/kernel_files/
          cp kernel_workspace/kernel_platform/common/fs/incfs/data_mgmt.c ./kernel_workspace/kernel_files/

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
         name: co3kernel
         path: kernel_workspace/kernel_files/
